### ISSUE TITLE
Spade - Bitswap Retrieval Worker

### ISSUE THREAD

**Issue by jcace** [data-preservation-programs/RetrievalBot#32]
- Modify/update the Bitswap retrieval worker to support the new `retrieve_type: spade` retrievals
- This is a different type of retrieval from the _standard_ bitswap retrievals, as it requires a **3-layer traversal** to be done, starting with the source CID and working down 2 layers of the tree to the leaves (data nodes) 
- This is due to how CIDs for DAGhouse are assembled - see https://github.com/filecoin-project/go-dagaggregator-unixfs#grouping-unixfs-structure

**Comment by xmcai2016** [comment]
@jcace to link PR here if you want Stephen to look at it

**Comment by anjor** [comment]
@xinaxu @ribasushi  need your review + merge on this before closing.

**Comment by jcace** [comment]
WIP at https://github.com/data-preservation-programs/RetrievalBot/pull/33

Runs separately as a spike for testing, still needs integration done. More details in the PR.

**Comment by jcace** [comment]
Still WIP, solving a bug with the Bitswap libp2p code
