### ISSUE TITLE
[Dashboard] Add some text explaining where the data came from

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/RetrievalBot#35]
Add some text on https://retrievalbot-dashboard.vercel.app/ to explain that the data came from retrieval bot instances run by PL, FF, Slingshot etc.

**Comment by jlogelin** [comment]
moved to https://github.com/data-preservation-programs/retrievalbot-dashboard/issues/12

**Comment by xmcai2016** [comment]
great progress @jlogelin! Let's add a few more to the list: the data came from retrieval bot instances run by PL, FF, Slingshot, **Gravity Assist, New Web Group, Triton, etc.**
