### ISSUE TITLE
[Dashboard] Change any mention of "HTTP Retrieval" to "HTTP Piece Retrieval"

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/RetrievalBot#44]
https://filecoinproject.slack.com/archives/C03UVDVVCDR/p1696252213163749?thread_ts=1696239051.458289&cid=C03UVDVVCDR

![Image](https://github.com/data-preservation-programs/RetrievalBot/assets/22433151/968f369d-01dc-4047-b05e-ad1f87d966c0)

**Comment by stephen-pl** [comment]
@xmcai2016  I dont notice any http retrieval mentioned in the code. Is this task to change things like

HTTP Total Call Count Last 30 days
HTTP Piece RetrievalTotal Call Count Last 30 days

**Comment by xmcai2016** [comment]
Yes it's referring to the front end (RB vercel dashboard), I should've been
more clear

**Comment by stephen-pl** [comment]
Solike 
![image](https://github.com/data-preservation-programs/RetrievalBot/assets/139834872/4a5b4975-28ad-45a5-9132-7199ca4ae562)

**Comment by stephen-pl** [comment]
The http inside the bar graphs come from the data in the db so not sure if we want to change that to be http_piece. We can just let me know

**Comment by stephen-pl** [comment]
Yes the places inside the graph. 

Will do that was just a quick change to understand if those were the places you were thinking about the changes. 

Ill have the pr out and merged soon to change HTTP to HTTP Piece in the side bar and the total counts
