### ISSUE TITLE
Retrieval Bot instance for Spade

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/RetrievalBot#45]
Description: we are going to stand up a separate instance of the retrieval bot for Spade due to spade tenant requirements

ETA: 2023-10-07
Maintainer: @stephen-pl

**Comment by xmcai2016** [comment]
@stephen-pl we will need the Spade instance to have the ability to queue its own tasks as opposed to listening to a centralized orchestrator (the shared task queue on mongo for the other retrieval bots). The work queue for this instance if completely separate from the other the retrieval bots.

**Comment by xmcai2016** [comment]
The test results from this RB instance should also live in a separate database to be used by Spade tenant service.

**Comment by xmcai2016** [comment]
@stephen-pl After we stand up the instance & have our own database on Mongo, we can consider sharing an aggregate copy of the data with SP Reputation WG. 
Instead of sending it to repWG's mongo db, I suggest we experiment with directly sending it to Polybase. What I'm thinking looks something like this: 
<img width="924" alt="image" src="https://github.com/data-preservation-programs/RetrievalBot/assets/22433151/e8b006d5-2b1c-4839-88ff-4f93e5f8780d">
https://excalidraw.com/#room=e68390ffd6446bd72a2d,Geno6eObBwesrdfqDigRtg

**Comment by stephen-pl** [comment]
Do you want to create a separate task for that or should it be part of this one?
