### ISSUE TITLE
Inaccurate log information

### ISSUE THREAD

**Issue by simlecode** [data-preservation-programs/RetrievalBot#6]
![image](https://github.com/data-preservation-programs/RetrievalBot/assets/69969590/8df5fd34-f298-4604-94d1-6c36678cb315)

![image](https://github.com/data-preservation-programs/RetrievalBot/assets/69969590/708241e2-06f3-4c3c-a0b6-3daaf0e13a34)

**Comment by xinaxu** [comment]
Thanks for identifying the bug. This is fixed in #13
